#ifndef _H_hardware_h
#define _H_hardware_h

#include "msp430hardware.h"

// LEDs
TOSH_ASSIGN_PIN(RED_LED, 4, 0);
TOSH_ASSIGN_PIN(GREEN_LED, 4, 1);
TOSH_ASSIGN_PIN(YELLOW_LED, 4, 2);

// CC2520 RADIO #defines
/*
TOSH_ASSIGN_PIN(RADIO_CCA, 1, 1);
TOSH_ASSIGN_PIN(RADIO_CSN, 5, 0);
TOSH_ASSIGN_PIN(RADIO_FIFO, 1, 5);
TOSH_ASSIGN_PIN(RADIO_FIFOP, 1, 6);
TOSH_ASSIGN_PIN(RADIO_RSTN, 5, 7);
TOSH_ASSIGN_PIN(RADIO_SFD, 1, 2);
TOSH_ASSIGN_PIN(RADIO_VREN, 1, 0);

TOSH_ASSIGN_PIN(CC_FIFOP, 1, 6);
TOSH_ASSIGN_PIN(CC_FIFO, 1, 5);
TOSH_ASSIGN_PIN(CC_SFD, 1, 2);
TOSH_ASSIGN_PIN(CC_VREN, 1, 0);
TOSH_ASSIGN_PIN(CC_RSTN, 5, 7);

TOSH_ASSIGN_PIN(UCLK, 5, 3);
TOSH_ASSIGN_PIN(SOMI, 5, 2);
TOSH_ASSIGN_PIN(SIMO, 5, 1);
*/

TOSH_ASSIGN_PIN(SOMI0, 3, 2);
TOSH_ASSIGN_PIN(SIMO0, 3, 1);
TOSH_ASSIGN_PIN(UCLK0, 3, 3);
TOSH_ASSIGN_PIN(UTXD0, 3, 4);
TOSH_ASSIGN_PIN(URXD0, 3, 5);
TOSH_ASSIGN_PIN(UTXD1, 3, 6);
TOSH_ASSIGN_PIN(URXD1, 3, 7);
TOSH_ASSIGN_PIN(UCLK1, 5, 3);
TOSH_ASSIGN_PIN(SOMI1, 5, 2);
TOSH_ASSIGN_PIN(SIMO1, 5, 1);

//User Interupt Pin
//TOSH_ASSIGN_PIN(USERINT, 2, 5);

/*
void TOSH_SET_PIN_DIRECTIONS(void)
{
	P1SEL = 0x00;
	P1DIR = 0x91;
	P1OUT = 0x00;
	
	P2SEL = 0x00;
	P2DIR = 0xdf;
	P2OUT = 0x00;
	
	P3SEL = 0x00;
	P3DIR = 0xff;
	P3OUT = 0x00;
	
	P4SEL = 0x00;
	P4DIR = 0xff;
	P4OUT = 0x00;
	
	P5SEL = 0x0e;
	P5DIR = 0xff;
	P5OUT = 0x80;
	
	P6SEL = 0x00;
	P6DIR = 0xff;
	P6OUT = 0x00;
}
*/
#endif // _H_hardware_h
